version: '3'
services:
  # nginx:
  # image: nginx:latest
  # container_name: nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /Users/qiaobo/Workspace/docker/nginx/www:/var/www/html
  #     - /Users/qiaobo/Workspace/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - /Users/qiaobo/Workspace/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
  #     - /Users/qiaobo/Workspace/docker/nginx/logs:/var/log/nginx

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass vhdDeJfsunPA5nIUiizP'

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678

